### ISSUE TITLE
doc: Add documentation

### ISSUE THREAD

**Issue by blacksmithop** [blacksmithop/KnowledgeRepo#2]

**Comment by singhvibhanshu** [comment]
Can you provide some details about what documentation you need?

**Comment by blacksmithop** [comment]
@singhvibhanshu the idea behind this project is to create a knowledge repository that users can contribute to as they see fit.
For starters, you can contribute towards a more descriptive Readme file. The other features are currently in development

**Comment by blacksmithop** [comment]
Closed by #8
