### ISSUE TITLE
feat: Database

### ISSUE THREAD

**Issue by blacksmithop** [blacksmithop/KnowledgeRepo#4]
MongoDB sounds like a good fit

**Comment by mariannerv** [comment]
I've worked with MongoDB before, I'd be happy to help if you need!

**Comment by blacksmithop** [comment]
@mariannerv  Sounds great. I'm currently using a JSON file over at https://github.com/blacksmithop/KnowledgeRepo/blob/main/app/utils/fake_database.py you can contribute with class that uses MongoDB instead!

**Comment by mariannerv** [comment]
Awesome!

**Comment by mariannerv** [comment]
@blacksmithop I just did a PR with the changed :)

**Comment by blacksmithop** [comment]
Closed in #9
