### ISSUE TITLE
feat: A more comprehensive UI

### ISSUE THREAD

**Issue by blacksmithop** [blacksmithop/KnowledgeRepo#6]

**Comment by Saiharitha3** [comment]
Hi @blacksmithop i will provide my help here can you please assign this issue

**Comment by blacksmithop** [comment]
@Saiharitha3 sounds great. Try running this project locally or in a [Codespace](https://github.com/codespaces) and see what you can improve for the UI. Pull requests are welcome

**Comment by Saiharitha3** [comment]
Thank you! Sure.

**Comment by blacksmithop** [comment]
Closed by #11
